"""initial

Revision ID: 0001
Revises:
Create Date: 2026-10-03 23:16:39.574857
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('allows_write', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('full', sa.Text(), nullable=False),
    sa.Column('mini', sa.Text(), nullable=False),
    sa.Column('anchor', sa.Text(), nullable=False),
    sa.Column('reward', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('active', 'paused')", name='habit_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('habit_pauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_pauses_habit_id'), 'habit_pauses', ['habit_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind in ('full', 'mini')", name='mark_kind'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='marks_one_per_day')
    )
    op.create_table('reminders',
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('days', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('evening', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('habit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('marks')
    op.drop_index(op.f('ix_habit_pauses_habit_id'), table_name='habit_pauses')
    op.drop_table('habit_pauses')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_table('users')
    # ### end Alembic commands ###
