"""reminder last sent

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 23:37:05.053746
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('last_morning_on', sa.Date(), nullable=True))
    op.add_column('reminders', sa.Column('last_evening_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'last_evening_on')
    op.drop_column('reminders', 'last_morning_on')
    # ### end Alembic commands ###
